#' Generate a formatted Scarab table from viability assay data
#'
#' This function creates a comprehensive summary table in the Scarab format for
#' viability assays (e.g. CellTiter-Glo), combining data from raw results and
#' dose-response curve fitting. The table includes experimental metadata, quality
#' control metrics, curve parameters, and raw viability values for each compound.
#'
#' @param results_list List containing raw experimental results from multiple plates,
#'   typically generated by the \code{\link{batch_viability_analysis}} function.
#'   Must contain plate-specific data with modified viability tables and quality metrics.
#' @param drc_results_list List containing dose-response curve fitting results,
#'   typically generated by the \code{\link{batch_drc_analysis}} function.
#'   Must contain final summary tables for each plate.
#' @param plate_name Character string specifying which plate to process.
#'   Should match a plate name in both \code{results_list} and \code{drc_results_list}
#'   (e.g., \code{"plate_01"}, \code{"plate_02"}). Default is \code{"plate_01"}.
#' @param date Character string with experiment date in format \code{"YYMMDD"}.
#'   Used to construct Experiment IDs. Default is \code{"260303"}.
#' @param experimenter_abbrev Character string with experimenter initials.
#'   Used to construct Experiment IDs. Default is \code{"JD"}.
#' @param sgc_compound_id Character string or NA with SGC global compound identifier/batch
#'   number. Applied to all compounds in the plate. Default is \code{NA}.
#' @param cell_line Character string with cell line used. Default is \code{"HeLa"}.
#' @param cell_type Character string describing the cell type (e.g. \code{"gastric adenocarcinoma"},
#'   \code{"human hepatoma"}). Default is \code{"cervical adenocarcinoma"}.
#' @param treatment_time Character string with treatment duration (e.g. \code{"72h"},
#'   \code{"48h"}). Default is \code{"72h"}.
#' @param measurement_method Character string describing the viability measurement method
#'   (e.g. \code{"CellTiter-Glo"}, \code{"resazurin"}). Default is \code{"CellTiter-Glo"}.
#' @param assay_volume Character string with assay volume in uL. Default is \code{"40"}.
#' @param plate_format Character string with plate format. Default is \code{"384-well"}.
#' @param plate_manufacturer Character string with plate manufacturer/catalog number.
#'   Default is \code{"3570"}.
#' @param plate_material Character string with plate material. Default is \code{"PS"}.
#' @param eln_id Character string or NA with Electronic Lab Notebook ID. Default is \code{NA}.
#' @param comments Character string or NA with additional comments. Default is \code{NA}.
#' @param fit_used Character string describing the fitting model used.
#'   Default is \code{"log(inhibitor) vs. response (three parameters)"}.
#' @param save Logical indicating whether to save the table as an Excel file.
#'   Default is \code{TRUE}.
#' @param file_name Character string or NULL for custom file name.
#'   If NULL, generates \code{"scarab_viability_<plate_name>.xlsx"}.
#'   Default is \code{NULL}.
#' @param decimal_separator Character specifying decimal separator for numeric values.
#'   Must be either \code{"."} (dot) or \code{","} (comma). Default is \code{"."}.
#'
#' @return A data frame with 67 rows and multiple columns (one per unique compound).
#'   The first column \code{"Field"} contains the parameter names; subsequent columns
#'   contain data for each compound. Compounds or constructs with NA names are excluded.
#'
#' @details
#' This function is designed to work with the output of:
#' \itemize{
#'   \item \code{\link{batch_viability_analysis}}: generates \code{results_list}
#'   \item \code{\link{batch_drc_analysis}}: generates \code{drc_results_list}
#' }
#'
#' \strong{Table structure (67 rows):}
#' \itemize{
#'   \item Rows 1-7: Basic information (cell line, cell type, treatment time, compound,
#'     experiment ID, SGC ID, measurement method)
#'   \item Rows 8-15: Curve parameters (LogIC50, IC50, HillSlope, R2, etc.)
#'   \item Rows 16-25: Quality control metrics (Mean/SD of controls, CV\%,
#'     signal-to-background, overall quality)
#'   \item Rows 26-29: Plate specifications
#'   \item Rows 30-41: LOG compound concentrations 1-12
#'   \item Rows 42-53: Compound viability values (replicate 1)
#'   \item Rows 54-65: Compound viability values (replicate 2 / duplicate)
#'   \item Rows 66-67: ELN ID, Comments
#' }
#'
#' Quality metrics are recomputed from the raw viability data stored in
#' \code{processing_info} and use CV\%-based quality assessment (not Z'/assay window,
#' which are NanoBRET-specific).
#'
#' Compounds or constructs whose name is \code{NA}, \code{NA_2}, \code{NA:NA},
#' or similar NA-derived placeholders are automatically excluded from the output.
#'
#' @seealso
#' \code{\link{batch_viability_analysis}} for generating the input \code{results_list},
#' \code{\link{batch_drc_analysis}} for generating the input \code{drc_results_list},
#' \code{\link{scarab_table}} for the equivalent NanoBRET version.
#'
#' @examples
#' \dontrun{
#' # Basic usage
#' table1 <- scarab_viability(results, drc_results, plate_name = "plate_01")
#'
#' # With experimental metadata
#' table2 <- scarab_viability(
#'   results, drc_results,
#'   plate_name          = "plate_01",
#'   date                = "260521",
#'   experimenter_abbrev = "TL",
#'   cell_line           = "HCT116",
#'   cell_type           = "adherent",
#'   treatment_time      = "72h",
#'   measurement_method  = "CellTiter-Glo"
#' )
#'
#' # European decimal format
#' table3 <- scarab_viability(results, drc_results, decimal_separator = ",")
#' }
#'
#' @importFrom openxlsx write.xlsx
#' @export

scarab_viability <- function(results_list,
                             drc_results_list,
                             plate_name          = "plate_01",
                             date                = "260303",
                             experimenter_abbrev = "JD",
                             sgc_compound_id     = NA,
                             cell_line           = "HeLa",
                             cell_type           = "cervical adenocarcinoma",
                             treatment_time      = "72h",
                             measurement_method  = "CellTiter-Glo",
                             assay_volume        = "40",
                             plate_format        = "384-well",
                             plate_manufacturer  = "3570",
                             plate_material      = "PS",
                             eln_id              = NA,
                             comments            = NA,
                             fit_used            = "log(inhibitor) vs. response (three parameters)",
                             save                = TRUE,
                             file_name           = NULL,
                             decimal_separator   = ".") {

  # -- Validate decimal separator --------------------------------------------
  if (!decimal_separator %in% c(".", ","))
    stop("decimal_separator must be either '.' or ','")

  # -- Helper: format numbers with correct decimal separator -----------------
  format_number <- function(x, digits = NULL) {
    if (is.null(x)) return(NA_character_)
    if (length(x) > 1)
      return(sapply(x, function(val) format_number(val, digits)))
    if (is.na(x) || identical(x, "<NA>") || identical(x, "NA"))
      return(NA_character_)
    x_num <- suppressWarnings(as.numeric(x))
    if (is.na(x_num))
      return(as.character(x))
    if (decimal_separator == ".") {
      if (!is.null(digits)) as.character(round(x_num, digits))
      else                   as.character(x_num)
    } else {
      num_str <- if (!is.null(digits)) format(round(x_num, digits), nsmall = digits)
                 else                  as.character(x_num)
      gsub("\\.", ",", num_str)
    }
  }


  # -- Internal helper: recompute viability quality metrics ------------------
  compute_quality <- function(result) {
  
    proc_info        <- result$processing_info
    if (is.null(proc_info)) return(NULL)
  
    viability_data   <- proc_info$viability_data
    control_0_info   <- proc_info$control_0_info
    control_100_info <- proc_info$control_100_info
    info_tbl         <- proc_info$info_table
  
    if (is.null(viability_data) || is.null(control_0_info) ||
        is.null(control_100_info) || is.null(info_tbl)) return(NULL)
  
    if (!"Construct_Modified" %in% colnames(info_tbl))
      info_tbl$Construct_Modified <- info_tbl[[3]]
  
    plate_row_values  <- info_tbl[[2]]
    construct_values  <- info_tbl$Construct_Modified
    unique_constructs <- unique(construct_values)
  
    row_index_map <- stats::setNames(seq_len(16L), LETTERS[seq_len(16L)])
  
    construct_groups <- lapply(
      stats::setNames(unique_constructs, unique_constructs),
      function(cn) {
        rows <- plate_row_values[construct_values == cn]
        as.integer(row_index_map[rows])
      }
    )
    construct_groups <- Filter(function(x) length(x) > 0L, construct_groups)
  
    ctrl0_col   <- control_0_info$name
    ctrl100_col <- control_100_info$name
  
    if (!ctrl0_col   %in% colnames(viability_data) ||
        !ctrl100_col %in% colnames(viability_data)) return(NULL)
  
    cv_quality_level <- function(cv_val) {
      if (is.na(cv_val))  return("insufficient (NA)")
      if (cv_val <= 10)   return("high (<=10%)")
      if (cv_val <= 20)   return("medium (10-20%)")
      return("low (>20%)")
    }
  
    lowest_quality <- function(...) {
      quality_order <- c("insufficient", "low", "medium", "high")
      lvls <- c(...)
      first_words <- vapply(lvls, function(x) {
        if (is.null(x) || is.na(x) || identical(x, "")) return("insufficient")
        strsplit(as.character(x), " ", fixed = TRUE)[[1L]][1L]
      }, character(1L), USE.NAMES = FALSE)
      scores <- match(first_words, quality_order)
      scores[is.na(scores)] <- 1L
      quality_order[min(scores)]
    }
  
    rows_list <- lapply(names(construct_groups), function(cn) {
      valid_rows <- construct_groups[[cn]]
      valid_rows <- valid_rows[
        !is.na(valid_rows) & valid_rows >= 1L & valid_rows <= nrow(viability_data)
      ]
      if (length(valid_rows) == 0L) return(NULL)
  
      bg_vals  <- viability_data[valid_rows, ctrl0_col]
      pos_vals <- viability_data[valid_rows, ctrl100_col]
  
      mean_bg  <- mean(bg_vals,  na.rm = TRUE)
      sd_bg    <- stats::sd(bg_vals,  na.rm = TRUE)
      mean_pos <- mean(pos_vals, na.rm = TRUE)
      sd_pos   <- stats::sd(pos_vals, na.rm = TRUE)
  
      cv_bg  <- if (!is.na(mean_bg)  && abs(mean_bg)  > 1e-9)
        (sd_bg  / mean_bg)  * 100 else NA_real_
      cv_pos <- if (!is.na(mean_pos) && abs(mean_pos) > 1e-9)
        (sd_pos / mean_pos) * 100 else NA_real_
  
      sb_ratio <- if (!is.na(mean_bg) && abs(mean_bg) > 1e-9)
        mean_pos / mean_bg else NA_real_
  
      cv_bg_comment  <- cv_quality_level(cv_bg)
      cv_pos_comment <- cv_quality_level(cv_pos)
      overall        <- lowest_quality(cv_bg_comment, cv_pos_comment)
  
      row_range <- paste(LETTERS[range(valid_rows)], collapse = "-")
  
      data.frame(
        Construct            = cn,
        Mean_Positive_Ctrl   = round(mean_pos,  3L),
        SD_Positive_Ctrl     = round(sd_pos,    3L),
        Mean_Background      = round(mean_bg,   3L),
        SD_Background        = round(sd_bg,     3L),
        CV_Background_pct    = round(cv_bg,     2L),
        CV_Positive_Ctrl_pct = round(cv_pos,    2L),
        CV_Background_Comment = cv_bg_comment,
        CV_PosCtrl_Comment   = cv_pos_comment,
        Overall_Quality      = overall,
        Signal_to_Background = round(sb_ratio,  3L),
        Rows                 = paste0(cn, " (", row_range, ")"),
        Rows_Count           = length(valid_rows),
        stringsAsFactors     = FALSE
      )
    })
  
    rows_df <- do.call(rbind, Filter(Negate(is.null), rows_list))
    if (is.null(rows_df) || nrow(rows_df) == 0L) return(NULL)
  
    # Transpose: constructs as columns, metrics as rows
    metrics_cols <- setdiff(colnames(rows_df), "Construct")
    mat          <- as.data.frame(t(rows_df[, metrics_cols, drop = FALSE]))
    colnames(mat) <- rows_df$Construct
    mat
  }

  # -- Access plate data -----------------------------------------------------
  plate_results <- results_list[[plate_name]]
  plate_drc     <- drc_results_list$drc_results[[plate_name]]

  if (is.null(plate_results))
    stop("Plate '", plate_name, "' not found in results_list. ",
         "Available plates: ", paste(names(results_list), collapse = ", "))
  if (is.null(plate_drc))
    stop("Plate '", plate_name, "' not found in drc_results_list. ",
         "Available plates: ",
         paste(names(drc_results_list$drc_results), collapse = ", "))

  # -- Extract tables --------------------------------------------------------
  # batch_viability_analysis renames $modified_table -> $modified_ratio_table
  result         <- plate_results$result
  modified_table <- result$modified_ratio_table
  final_summary  <- plate_drc$drc_result$final_summary_table

  if (is.null(modified_table))
    stop("Could not find modified_ratio_table in results_list[['", plate_name,
         "']]$result. Make sure results_list comes from batch_viability_analysis().")
  if (is.null(final_summary))
    stop("Could not find final_summary_table in drc_results_list for plate '",
         plate_name, "'.")

  # -- Recompute quality metrics from processing_info -------------------------
  # batch_viability_analysis computes quality metrics internally but does NOT
  # store them in $result. compute_quality() (defined above) recomputes them
  # from the raw viability data in $processing_info.
  quality_table <- compute_quality(result)

  # -- Helper: is a name an NA placeholder? -----------------------------------
  # Catches: NA, NA_2, NA.2, NA:NA, NA_2:NA_2, etc.
  is_na_name <- function(x) {
    if (is.na(x)) return(TRUE)
    x <- trimws(x)
    grepl("^NA(_\\d+)?(\\.2)?$",   x, ignore.case = TRUE) ||
      grepl("^NA(_\\d+)?:NA",      x, ignore.case = TRUE)
  }

  # -- Identify compound columns --------------------------------------------
  log_col_name  <- colnames(modified_table)[1]   # always the log(inhibitor) column

  # Filter 1: drop the log column and any column whose full name is NA-like
  compound_cols <- colnames(modified_table)[
    colnames(modified_table) != log_col_name &
    !sapply(colnames(modified_table), is_na_name)
  ]

  base_names <- gsub("\\.2$", "", compound_cols)

  # Filter 2: also drop entries where the construct part (before ":") is NA-like
  construct_part <- vapply(base_names, function(nm) {
    if (grepl(":", nm)) trimws(strsplit(nm, ":")[[1]][1]) else nm
  }, character(1L), USE.NAMES = FALSE)

  keep          <- !sapply(construct_part, is_na_name)
  compound_cols <- compound_cols[keep]
  base_names    <- base_names[keep]

  unique_compounds <- unique(base_names)

  # -- Extract log concentrations --------------------------------------------
  # Row 1 = 0% control (NA log conc), rows 2:(n-1) = experimental, row n = 100% ctrl
  log_col_vals <- modified_table[[log_col_name]]
  n_rows_mod   <- nrow(modified_table)
  exp_row_idx  <- 2:(n_rows_mod - 1)
  log_concs    <- format_number(as.numeric(log_col_vals[exp_row_idx]), digits = 2)
  n_concs      <- min(length(log_concs), 12L)

  # -- Define the 67 row labels ----------------------------------------------
  # Rows 16-25 use the exact viability quality metric names.
  rows <- c(
    "Cell line",                                          #  1
    "Cell Type",                                          #  2
    "Treatment Time",                                     #  3
    "Compound",                                           #  4
    "Experiment ID",                                      #  5
    "SGC Global Compound ID (Batch)",                     #  6
    "Measurement Method",                                 #  7
    "LogIC50",                                            #  8
    "IC50, [M]",                                          #  9
    "IC50 comment",                                       # 10
    "HillSlope",                                          # 11
    "R squared",                                          # 12
    "no. of Y-points",                                    # 13
    "Fit used",                                           # 14
    "IC50 Curve comment",                                 # 15
    "Mean_Positive_Ctrl",                                 # 16
    "SD_Positive_Ctrl",                                   # 17
    "Mean_Background",                                    # 18
    "SD_Background",                                      # 19
    "CV_Background_pct",                                  # 20
    "CV_Positive_Ctrl_pct",                               # 21
    "CV_Background_Comment",                              # 22
    "CV_PosCtrl_Comment",                                 # 23
    "Signal_to_Background",                               # 24
    "Overall_Quality",                                    # 25
    "Assay volume used [302265L]",                        # 26
    "Plate format used",                                  # 27
    "Plate Manufacturer (Catalog No.)",                   # 28
    "Plate material used",                                # 29
    paste0("LOG Compound Concentration ", 1:12),          # 30-41
    paste0("Compound Concentration ", 1:12),              # 42-53
    paste0("Compound Concentration ", 1:12, "-Duplicate"),# 54-65
    "ELN ID",                                             # 66
    "Comments"                                            # 67
  )

  # QC metrics in order (rows 16-25); row name == metric name (direct 1:1)
  qc_metrics <- c(
    "Mean_Positive_Ctrl",    # 16
    "SD_Positive_Ctrl",      # 17
    "Mean_Background",       # 18
    "SD_Background",         # 19
    "CV_Background_pct",     # 20
    "CV_Positive_Ctrl_pct",  # 21
    "CV_Background_Comment", # 22
    "CV_PosCtrl_Comment",    # 23
    "Signal_to_Background",  # 24
    "Overall_Quality"        # 25
  )

  # Which QC metrics are numeric (format with decimal separator)
  numeric_qc_metrics <- c(
    "Mean_Positive_Ctrl", "SD_Positive_Ctrl",
    "Mean_Background",    "SD_Background",
    "CV_Background_pct",  "CV_Positive_Ctrl_pct",
    "Signal_to_Background"
  )

  # -- Build base data frame ------------------------------------------------
  table_out <- data.frame(Field = rows, stringsAsFactors = FALSE)

  # -- Fill one column per unique compound ----------------------------------
  for (i in seq_along(unique_compounds)) {
    compound_full <- unique_compounds[i]   # e.g. "LRRK2:JQ1"

    # Split into construct (before ":") and compound (after ":")
    if (grepl(":", compound_full)) {
      parts     <- strsplit(compound_full, ":")[[1]]
      construct <- trimws(parts[1])
      compound  <- trimws(paste(parts[-1], collapse = ":"))
    } else {
      construct <- compound_full
      compound  <- compound_full
    }

    # Locate main and duplicate columns
    main_col <- compound_cols[base_names == compound_full & !grepl("\\.2$", compound_cols)]
    dup_col  <- compound_cols[base_names == compound_full &  grepl("\\.2$", compound_cols)]

    col_data <- rep(NA_character_, length(rows))

    # -- Rows 1-7: Basic information ------------------------------------------
    col_data[1] <- cell_line
    col_data[2] <- as.character(cell_type)
    col_data[3] <- as.character(treatment_time)
    col_data[4] <- compound
    col_data[5] <- paste(date, experimenter_abbrev, construct, compound, sep = "-")
    col_data[6] <- as.character(sgc_compound_id)
    col_data[7] <- as.character(measurement_method)

    # -- Rows 8-15: Curve parameters ------------------------------------------
    if (!is.null(final_summary) && compound_full %in% colnames(final_summary)) {
      sc <- compound_full

      v <- final_summary["LogIC50", sc]
      if (!is.na(v) && v != "<NA>")
        col_data[8] <- format_number(v, digits = 2)

      v <- final_summary["IC50", sc]
      if (!is.na(v) && v != "<NA>")
        col_data[9] <- if (decimal_separator == ",") gsub("\\.", ",", v) else v

      for (rn in c("IC50_comment", "IC50 comment", "ic50_comment")) {
        if (rn %in% rownames(final_summary)) {
          v <- final_summary[rn, sc]
          if (!is.na(v) && v != "<NA>") { col_data[10] <- v; break }
        }
      }

      v <- final_summary["Ideal_Hill_Slope", sc]
      if (!is.na(v) && v != "<NA>")
        col_data[11] <- format_number(v, digits = 2)

      v <- final_summary["R_squared", sc]
      if (!is.na(v) && v != "<NA>")
        col_data[12] <- format_number(v, digits = 2)

      v <- final_summary["Degrees_of_Freedom", sc]
      if (!is.na(v) && v != "<NA>") {
        n_y <- suppressWarnings(as.numeric(v))
        if (!is.na(n_y)) col_data[13] <- as.character(n_y + 3)
      }

      col_data[14] <- fit_used

      v <- final_summary["Curve_Quality", sc]
      if (!is.na(v) && v != "<NA>")
        col_data[15] <- tolower(v)
    }

    # -- Rows 16-25: Quality control ------------------------------------------
    # quality_table rows = metric names, cols = construct names (direct 1:1 mapping)
    qc_col <- if (!is.null(quality_table) && construct %in% colnames(quality_table))
      construct else NULL

    if (!is.null(qc_col)) {
      for (j in seq_along(qc_metrics)) {
        metric <- qc_metrics[j]
        v <- if (metric %in% rownames(quality_table))
               quality_table[metric, qc_col] else NA_character_
        v <- if (is.na(v) || identical(v, "<NA>")) NA_character_ else as.character(v)
        col_data[15L + j] <- if (metric %in% numeric_qc_metrics)
          format_number(v, digits = 2) else v
      }
    }

    # -- Rows 26-29: Plate specifications -------------------------------------
    col_data[26] <- assay_volume
    col_data[27] <- plate_format
    col_data[28] <- plate_manufacturer
    col_data[29] <- plate_material

    # -- Rows 30-41: LOG concentrations ---------------------------------------
    for (j in seq_len(n_concs))
      col_data[29L + j] <- log_concs[j]

    # -- Rows 42-53: Viability values (replicate 1) ---------------------------
    if (length(main_col) > 0) {
      exp_vals <- modified_table[[main_col[1]]][exp_row_idx]
      for (j in seq_len(min(length(exp_vals), 12L)))
        col_data[41L + j] <- format_number(exp_vals[j])
    }

    # -- Rows 54-65: Viability values (duplicate) -----------------------------
    if (length(dup_col) > 0) {
      exp_vals_dup <- modified_table[[dup_col[1]]][exp_row_idx]
      for (j in seq_len(min(length(exp_vals_dup), 12L)))
        col_data[53L + j] <- format_number(exp_vals_dup[j])
    }

    # -- Rows 66-67: Metadata -------------------------------------------------
    col_data[66] <- as.character(eln_id)
    col_data[67] <- as.character(comments)

    # -- Attach column --------------------------------------------------------
    col_label <- if (i == 1L) "X4" else paste0("X", i + 3L)
    table_out[[col_label]] <- col_data
  }

  # -- Save -------------------------------------------------------------------
  if (save) {
    if (!requireNamespace("openxlsx", quietly = TRUE))
      stop("Package 'openxlsx' is required. Install with: install.packages('openxlsx')")

    if (is.null(file_name)) {
      file_name <- paste0("scarab_viability_", plate_name, ".xlsx")
    } else {
      if (!grepl("\\.xlsx$", file_name))
        file_name <- paste0(file_name, ".xlsx")
    }

    openxlsx::write.xlsx(table_out, file = file_name, rowNames = FALSE, colNames = FALSE)
    message("Table saved as: ", file_name)
  }

  return(table_out)
}
